name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: app.py
      FLASK_PORT: 5000 # Configurable port

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Set environment variables
      run: echo "FLASK_APP=TestedServer/app.py" >> $GITHUB_ENV

    - name: Start Flask server
      run: |
        source .venv/bin/activate
        nohup flask run --host=0.0.0.0 -p $FLASK_PORT &
        sleep 15  # Wait for the server to start (adjust as needed)

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest tests